### ISSUE TITLE
Misfit Verification button not working

### ISSUE THREAD

**Issue by MedhaviKulshrestha** [orcasgit/python-misfit#7]
I am trying to set an endpoint URL  for my misfit account. CLicking on verify button with URL as "https://securemercerdev.www.marshinc.net/content/mercer-bbc/uk/en/provisioning/login.html" is showing as Verify failed, clickout time failed, Retry.

I am not geeting the issue exactly.
![misfit](https://cloud.githubusercontent.com/assets/23400670/20215122/66b51b64-a838-11e6-8da3-097c61ca3494.png)

**Comment by brad** [comment]
Did you set up a notifications end point as described [here](https://github.com/orcasgit/python-misfit/blob/master/README.rst#notifications)? That's what the URL should be. Not an HTML page

**Comment by MedhaviKulshrestha** [comment]
For other Auth2.0 apps, I have used this HTML page as end point. I need this page as redirect uri. What should  I do in this case?

**Comment by brad** [comment]
This library provides tools for integrating with Python endpoints. If you need to integrate with HTML then you will need to implement those parts yourself (such as SNS message decryption/encryption). See the Misfit docs for a full description of the process: https://build.misfit.com/docs/cloudapi/api_references#authorization-server-for-web

**Comment by brad** [comment]
One clear problem I do see is that your subscription hook URL endpoint has a different domain from the one specified for application domain. The Misfit API requires that the domains match

**Comment by MedhaviKulshrestha** [comment]
Hello Sir,
I have tried giving the same URL as both application domain and endpoint url. Still its giving the error as 302. See screenshot. Also, the url that I am trying to hit a URL as per the document given by your above comment. My URL is https://api.misfitwearables.com/auth/dialog/authorize?response_type=code&client_id=JTzwjX6OFL9F0zjy&redirect_uri=https://www.mercerharmonise.mercer.com.html&scope=public,birthday,email
This is giving me an invalid uri response saying that {"error":"invalid_request","error_description":"Invalid parameter: redirect_uri does not match any of registered application domains"}

Does it requires some time to update the application domain ? Because I have changed it to keep the same. Also, if not then what else can we do?
![misfiterror](https://cloud.githubusercontent.com/assets/23400670/20295291/1928a45c-ab2a-11e6-8474-770bc50a13a9.png)

**Comment by brad** [comment]
The redirect_uri in your example is www.mercerharmonise.mercer.com.html
which indeed does not match your application domain. Looks like maybe you
made a typo in the redirect_uri?

On Mon, Nov 14, 2016, 10:24 PM MedhaviKulshrestha <notifications@github.com>
wrote:

Hello Sir,
I have tried giving the same URL as both application domain and endpoint
url. Still its giving the error as 302. See screenshot. Also, the url that
I am trying to hit a URL as per the document given by your above comment.
My URL is
https://api.misfitwearables.com/auth/dialog/authorize?response_type=code&client_id=JTzwjX6OFL9F0zjy&redirect_uri=https://www.mercerharmonise.mercer.com.html&scope=public,birthday,email
This is giving me an invalid uri response saying that
{"error":"invalid_request","error_description":"Invalid parameter:
redirect_uri does not match any of registered application domains"}

Does it requires some time to update the application domain ? Because I
have changed it to keep the same. Also, if not then what else can we do?
[image: misfiterror]
<https://cloud.githubusercontent.com/assets/23400670/20295291/1928a45c-ab2a-11e6-8474-770bc50a13a9.png>

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/orcasgit/python-misfit/issues/7#issuecomment-260558170>,
or mute the thread

**Comment by MedhaviKulshrestha** [comment]
This worked. thank you for helping me so much with this.

**Comment by brad** [comment]
That's great! Happy to help
